# Generated by Django 4.2.7 on 2023-11-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UK_Estate_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("price", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("key_features", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("images", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "properties",
                "managed": False,
            },
        ),
    ]
