# Generated by Django 4.2.7 on 2024-01-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UK_Estate_app", "0002_property"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "interest",
                    models.CharField(
                        choices=[
                            ("buying", "Buying"),
                            ("selling", "Selling"),
                            ("renting", "Renting"),
                        ],
                        max_length=7,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                (
                    "propertyType",
                    models.CharField(
                        choices=[
                            ("house", "House"),
                            ("apartment", "Apartment"),
                            ("commercial", "Commercial"),
                        ],
                        max_length=11,
                    ),
                ),
                ("budget", models.CharField(max_length=100)),
                ("message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
